### ISSUE TITLE
[question] How to compile and run this editor?

### ISSUE THREAD

**Issue by BooAA** [guenchi/Emacs#1]
Sorry for newbie question. I'm new to chez scheme but I'm very interested in contributing to this project. However, I don't know where should I start to compile or running this editor. Need some helps. Thanks!

**Comment by evilbinary** [comment]
@BooAA hi, you can go down https://github.com/cisco/ChezScheme and compile.If you in scheme editor you chould also look this project .https://github.com/evilbinary/duck-editor

**Comment by guenchi** [comment]
```
$ cd schemas
$ cc -fPIC -shared emacs.c  -o emacs.so
$ scheme emacs.sc
```

"scheme" may be "chez" or "petit"  like  `chez emacs.sc`
